uploads = []
generated = []

[[outputs]]
id = "AZ7oaebbOd55rudJFmNum"
uri = "file://guides/DesignMyLife-User-Guide.docx"
type = "word_document"
title = "DesignMyLife User Guide (DOCX for Word)"

[[outputs]]
id = "hcD9oeBG3N2PiqoBPMRbw"
uri = "file://guides/DesignMyLife-User-Guide.tar.gz"
type = "unspecified"
title = "DesignMyLife User Guide (HTML + DOCX archive)"

[[outputs]]
id = "5OnsF4oTWCNkxia604IYi"
uri = "file://DesignMyLife-User-Guide.md"
type = "text"
title = "DesignMyLife User Guide"
